python3 modeling/score.py --mode preprocess --cnndm $PWD/../data/cnndm --summaries $PWD/../pointer-generator/checkpoint/pretrained_model_tf1.2.1/decode_test_400maxenc_4beam_35mindec_120maxdec_ckpt-238410/reference --evaluation $PWD/evaluation/test_sentence_reference_resolved --coref
python3 modeling/score.py --mode preprocess --cnndm $PWD/../data/cnndm --summaries $PWD/../pointer-generator/checkpoint/pretrained_model_tf1.2.1/decode_test_400maxenc_4beam_35mindec_120maxdec_ckpt-238410/reference --evaluation $PWD/evaluation/test_sentence_reference_unresolved
python3 modeling/score.py --mode preprocess --cnndm $PWD/../data/cnndm --summaries $PWD/../pointer-generator/checkpoint/pretrained_model_tf1.2.1/decode_test_400maxenc_4beam_35mindec_120maxdec_ckpt-238410/decoded --evaluation $PWD/evaluation/test_sentence_decoded_resolved --coref 
python3 modeling/score.py --mode preprocess --cnndm $PWD/../data/cnndm --summaries $PWD/../pointer-generator/checkpoint/pretrained_model_tf1.2.1/decode_test_400maxenc_4beam_35mindec_120maxdec_ckpt-238410/decoded --evaluation $PWD/evaluation/test_sentence_decoded_unresolved
python3 modeling/score.py --mode preprocess --cnndm $PWD/../data/cnndm --summaries $PWD/../pointer-generator/checkpoint/pretrained_model_tf1.2.1/decode_test_400maxenc_4beam_35mindec_120maxdec_ckpt-238410/reference --evaluation $PWD/evaluation/test_paragraph_reference_resolved --coref --paragraph
python3 modeling/score.py --mode preprocess --cnndm $PWD/../data/cnndm --summaries $PWD/../pointer-generator/checkpoint/pretrained_model_tf1.2.1/decode_test_400maxenc_4beam_35mindec_120maxdec_ckpt-238410/reference --evaluation $PWD/evaluation/test_paragraph_reference_unresolved --paragraph 
python3 modeling/score.py --mode preprocess --cnndm $PWD/../data/cnndm --summaries $PWD/../pointer-generator/checkpoint/pretrained_model_tf1.2.1/decode_test_400maxenc_4beam_35mindec_120maxdec_ckpt-238410/decoded --evaluation $PWD/evaluation/test_paragraph_decoded_resolved --coref --paragraph 
python3 modeling/score.py --mode preprocess --cnndm $PWD/../data/cnndm --summaries $PWD/../pointer-generator/checkpoint/pretrained_model_tf1.2.1/decode_test_400maxenc_4beam_35mindec_120maxdec_ckpt-238410/decoded --evaluation $PWD/evaluation/test_paragraph_decoded_unresolved --paragraph
python3 modeling/score.py --mode preprocess --cnndm $PWD/../data/cnndm --summaries $PWD/../pointer-generator/checkpoint/pretrained_model_tf1.2.1/decode_val_400maxenc_4beam_35mindec_120maxdec_ckpt-238410/reference --evaluation $PWD/evaluation/val_sentence_reference_resolved --coref 
python3 modeling/score.py --mode preprocess --cnndm $PWD/../data/cnndm --summaries $PWD/../pointer-generator/checkpoint/pretrained_model_tf1.2.1/decode_val_400maxenc_4beam_35mindec_120maxdec_ckpt-238410/reference --evaluation $PWD/evaluation/val_sentence_reference_unresolved 
python3 modeling/score.py --mode preprocess --cnndm $PWD/../data/cnndm --summaries $PWD/../pointer-generator/checkpoint/pretrained_model_tf1.2.1/decode_val_400maxenc_4beam_35mindec_120maxdec_ckpt-238410/decoded --evaluation $PWD/evaluation/val_sentence_decoded_resolved --coref
python3 modeling/score.py --mode preprocess --cnndm $PWD/../data/cnndm --summaries $PWD/../pointer-generator/checkpoint/pretrained_model_tf1.2.1/decode_val_400maxenc_4beam_35mindec_120maxdec_ckpt-238410/decoded --evaluation $PWD/evaluation/val_sentence_decoded_unresolved 
python3 modeling/score.py --mode preprocess --cnndm $PWD/../data/cnndm --summaries $PWD/../pointer-generator/checkpoint/pretrained_model_tf1.2.1/decode_val_400maxenc_4beam_35mindec_120maxdec_ckpt-238410/reference --evaluation $PWD/evaluation/val_paragraph_reference_resolved --coref --paragraph
python3 modeling/score.py --mode preprocess --cnndm $PWD/../data/cnndm --summaries $PWD/../pointer-generator/checkpoint/pretrained_model_tf1.2.1/decode_val_400maxenc_4beam_35mindec_120maxdec_ckpt-238410/reference --evaluation $PWD/evaluation/val_paragraph_reference_unresolved --paragraph
python3 modeling/score.py --mode preprocess --cnndm $PWD/../data/cnndm --summaries $PWD/../pointer-generator/checkpoint/pretrained_model_tf1.2.1/decode_val_400maxenc_4beam_35mindec_120maxdec_ckpt-238410/decoded --evaluation $PWD/evaluation/val_paragraph_decoded_resolved --coref --paragraph
python3 modeling/score.py --mode preprocess --cnndm $PWD/../data/cnndm --summaries $PWD/../pointer-generator/checkpoint/pretrained_model_tf1.2.1/decode_val_400maxenc_4beam_35mindec_120maxdec_ckpt-238410/decoded --evaluation $PWD/evaluation/val_paragraph_decoded_unresolved --paragraph
